version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-1_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mysample
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    env_file:
      - .env

  flask_app:
    image: aayushsingh2001/flask_mysql_app:0.3
    container_name: flask_container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: mysample
    ports:
      - "6123:5000"
    env_file:
      - .env

  nginx:
    image: aayushsingh2001/flask_reverse_proxy_nginx:0.3
    container_name: nginx_container
    restart: always
    depends_on:
      - flask_app
    ports:
      - "80:80"